### PR TITLE
feat: add download study dialog by adding ohif-idc-extension

### PR DESCRIPTION
**Pull request by pedrokohler**
### Context

Solves https://github.com/ImagingDataCommons/ViewersV3/issues/62

### Changes & Results

image
image

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Review by igoroctaviano — CHANGES_REQUESTED** [review]
It's looking good! You will need to add/install the extension to the package.json of the app folder since the link is just virtual (local). Here: https://github.com/ImagingDataCommons/ViewersV3/blob/26a8ff501ef181cf5525c6631c3606b4c5a5bb25/platform/app/package.json#L64

Also, since we are not using a publish npm package you need to point to the other repo's main branch e.g. https://github.com/ImagingDataCommons/ViewersV3/blob/26a8ff501ef181cf5525c6631c3606b4c5a5bb25/platform/app/package.json#L51

**Comment by pedrokohler** [comment]
> It's looking good! You will need to add/install the extension to the package.json of the app folder since the link is just virtual (local). Here:
> 
> https://github.com/ImagingDataCommons/ViewersV3/blob/26a8ff501ef181cf5525c6631c3606b4c5a5bb25/platform/app/package.json#L64
> 
> Also, since we are not using a publish npm package you need to point to the other repo's main branch e.g.
> 
> https://github.com/ImagingDataCommons/ViewersV3/blob/26a8ff501ef181cf5525c6631c3606b4c5a5bb25/platform/app/package.json#L51

@igoroctaviano I believe it's good to go now. Please check.

**Comment by fedorov** [comment]
Related to https://github.com/OHIF/Viewers/pull/4367

**Review by igoroctaviano — APPROVED** [review]
LGTM

**Comment by igoroctaviano** [comment]
@pedrokohler lets wait Andrey to test it before merge.

**Comment by fedorov** [comment]
Can you please include the updated screenshots, after the PR above is merged, since I expect the UI is different than in the original screenshot at the top of this thread?

Also, for the popup text, instead of "install the idc cli", can you please put "install the [idc-index](https://github.com/imagingdatacommons/idc-index) python package"?

**Comment by pedrokohler** [comment]
> Can you please include the updated screenshots, after the PR above is merged, since I expect the UI is different than in the original screenshot at the top of this thread?
> 
> Also, for the popup text, instead of "install the idc cli", can you please put "install the [idc-index](https://github.com/imagingdatacommons/idc-index) python package"?

 @fedorov:
 
image
image

The changes above were pushed.

**Comment by fedorov** [comment]
LGTM Pedro! If you can, could you hyperlink [idc-index](https://github.com/imagingdatacommons/idc-index)? This way the user can easily learn more about the package before installing it. If hyperlinking is not straightforward, it's fine with me to merge as is!

**Pull request merged**
